version: '2'
services:
    backend:
        build: ./src/backend
        environment:
          - NODE_ENV=development
          - MONGODB_USER="usermongo"
          - MONGODB_PASS="passmongo"
        volumes:
          - ./src/backend:/src:rw
        ports:
          - 3001:3001
          - 9229:9229
        links:
          - mongodb
        depends_on:
          - mongodb
    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="usermongo"
          - MONGODB_PASS="passmongo"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null