version: '2'
services:
    backend:
        image: node:slim
        environment:
          - NODE_ENV=development
          - MONGOURL=mongodb://mongodb:27017/
          - DB=almundo
          - COLLECTION=hotel
          - MONGODB_USER="usermongo"
          - MONGODB_PASS="passmongo"
        volumes:
          - ./src/backend:/src:rw
        ports:
          - 3001:3001
          - 9229:9229
        links:
          - mongodb
        depends_on:
          - mongodb
        command: bash -c "cd /src && yarn build && yarn start"
    frontend:
        image: node:slim
        environment:
          - NODE_ENV=development
        volumes:
          - ./src/frontend:/src:rw
        ports:
          - 4200:4200
        links:
          - backend
        depends_on:
          - backend
        command: bash -c "cd /src && yarn build && yarn start"
    mongodb:
        image: mongo:latest
        environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
          - MONGODB_USER="usermongo"
          - MONGODB_PASS="passmongo"
        volumes:
          - ./data/db:/data/db
        ports:
            - 27017:27017
        command: mongod --smallfiles --logpath=/dev/null